### ISSUE TITLE
API URL should be "speech-to-text" and not "text-to-speech"

### ISSUE THREAD

**Issue by dalehumby** [seifane/whisper-rhasspy-http#1]
The purpose of this API is to change "speech" into "text". The URL is currently called "text-to-speech" which is the process of turning a text string into a audio file (like a wav file)

Note in the Rhasspy docs for Remote HTTP, the example given is "speech-to-text"
Example: http://localhost:12101//api/speech-to-text

I suggest making the change on [line 29](https://github.com/seifane/whisper-rhasspy-http/blob/fe29bd619e29696b2ac3f794b008144c2a436330/main.py#L29) to 

```
@route('/api/speech-to-text', method='POST')
```

This will be a breaking change for those who have already used the current URL.

**Comment by seifane** [comment]
My bad. Made the change in https://github.com/seifane/whisper-rhasspy-http/commit/3f55a727f2880e6988ba5f51803b8b609f241d62
